# Generated by Django 5.2.3 on 2025-09-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_chief_editor",
            field=models.BooleanField(default=False, verbose_name="Baş Editör"),
        ),
    ]
