# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_chief_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_paylasim_izni',
            field=models.BooleanField(default=False, verbose_name='E-posta Adresimi Diğer Kullanıcılarla Paylaş'),
        ),
        migrations.AddField(
            model_name='user',
            name='ozgecmis_paylasim_izni',
            field=models.BooleanField(default=False, verbose_name='Özgeçmişimi Diğer Kullanıcılarla Paylaş'),
        ),
    ]

