# Generated by Django 5.2.3 on 2025-09-28 10:11

import core.security
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_privacy_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_resmi",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.profile_pic_path,
                validators=[core.security.validate_image_file],
                verbose_name="Profil Resmi",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=users.models.resume_path,
                validators=[core.security.validate_pdf_file],
                verbose_name="Özgeçmiş (PDF)",
            ),
        ),
    ]
