# Generated by Django 5.2.3 on 2025-06-22 12:45

import articles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DergiSayisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayi', models.CharField(max_length=100, unique=True, verbose_name='Dergi Sayısı/Adı')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dergi Sayısı',
                'verbose_name_plural': 'Dergi Sayıları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=255, verbose_name='Yazarın Adı Soyadı')),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
                'ordering': ['isim_soyisim'],
            },
        ),
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, help_text='Bu alan otomatik oluşturulur.', max_length=255, unique=True)),
                ('aciklama', models.TextField(verbose_name='Açıklama/Özet')),
                ('pdf_dosyasi', models.FileField(upload_to=articles.models.article_pdf_path, verbose_name='PDF Dosyası')),
                ('anahtar_kelimeler', models.CharField(blank=True, help_text='Kelimeleri virgül (,) ile ayırınız.', max_length=255, verbose_name='Anahtar Kelimeler')),
                ('admin_notu', models.TextField(blank=True, null=True, verbose_name='Editör/Admin Notu')),
                ('goruntulenme_sayisi', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('goster_makaleler_sayfasinda', models.BooleanField(default=False, verbose_name='Yayında mı?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('admin_notu_okundu', models.BooleanField(default=True)),
                ('dergi_sayisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makaleler', to='articles.dergisayisi', verbose_name='Dergi Sayısı')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
