# Generated by Django 5.2.3 on 2025-06-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yazar',
            name='user_hesabi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yazar_profili', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='makale',
            name='yazarlar',
            field=models.ManyToManyField(related_name='makaleler', to='articles.yazar', verbose_name='Yazarlar'),
        ),
    ]
