# Generated by Django 5.2.3 on 2025-09-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = []
