# Generated by Django 5.2.3 on 2025-09-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_auto_20250926_1955"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dergisayisi",
            options={
                "ordering": ["-yil", "-ay", "-sayi_no"],
                "verbose_name": "Dergi Sayısı",
                "verbose_name_plural": "Dergi Sayıları",
            },
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="ay",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Ocak"),
                    (2, "Şubat"),
                    (3, "Mart"),
                    (4, "Nisan"),
                    (5, "Mayıs"),
                    (6, "Haziran"),
                    (7, "Temmuz"),
                    (8, "Ağustos"),
                    (9, "Eylül"),
                    (10, "Ekim"),
                    (11, "Kasım"),
                    (12, "Aralık"),
                ],
                default=1,
                verbose_name="Ay",
            ),
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="cilt",
            field=models.PositiveIntegerField(
                default=46, help_text="Örn: 48", verbose_name="Cilt"
            ),
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="sayi_no",
            field=models.PositiveIntegerField(
                default=1, help_text="Örn: 15", verbose_name="Sayı No"
            ),
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="yayinlanma_tarihi",
            field=models.DateField(
                blank=True,
                help_text="Boş bırakılırsa otomatik olarak yıl-ay'dan hesaplanır",
                null=True,
                verbose_name="Yayınlanma Tarihi",
            ),
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="yil",
            field=models.PositiveIntegerField(
                default=2025, help_text="Örn: 2025", verbose_name="Yıl"
            ),
        ),
        migrations.AlterField(
            model_name="dergisayisi",
            name="sayi",
            field=models.CharField(max_length=100, verbose_name="Dergi Sayısı/Adı"),
        ),
    ]
