# Generated by Django 5.2.3 on 2025-09-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_dergisayisi_options_dergisayisi_ay_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dergisayisi",
            unique_together={("yil", "ay", "sayi_no")},
        ),
    ]
