# Generated by Django 5.2.3 on 2025-09-26 18:00

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_dergisayisi_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dergisayisi",
            name="sayi",
        ),
        migrations.RemoveField(
            model_name="dergisayisi",
            name="yayinlanma_tarihi",
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="kapak_gorseli",
            field=models.ImageField(
                blank=True,
                help_text="Yüklenmezse varsayılan kapak kullanılır",
                null=True,
                upload_to=articles.models.journal_cover_path,
                verbose_name="Kapak Görseli",
            ),
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="yayinlandi_mi",
            field=models.BooleanField(default=False, verbose_name="Yayınlandı mı?"),
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="yayinlanma_secimi",
            field=models.CharField(
                choices=[
                    ("yayinlanmasin", "Yayınlanmasın"),
                    ("simdi", "Şimdi Yayınlansın"),
                    ("ileri_tarih", "İleri Tarihte Yayınlansın"),
                ],
                default="yayinlanmasin",
                max_length=20,
                verbose_name="Yayınlanma Seçimi",
            ),
        ),
        migrations.AddField(
            model_name="dergisayisi",
            name="zamanli_yayinlanma_tarihi",
            field=models.DateTimeField(
                blank=True,
                help_text="İleri tarih seçeneği için gerekli",
                null=True,
                verbose_name="Zamanlı Yayınlanma Tarihi",
            ),
        ),
    ]
