# Generated by Django 5.2.3 on 2025-09-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_remove_dergisayisi_sayi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dergisayisi",
            name="zamanli_yayinlanma_tarihi",
        ),
        migrations.AlterField(
            model_name="dergisayisi",
            name="yayinlanma_secimi",
            field=models.CharField(
                choices=[
                    ("yayinlanmasin", "Yayınlanmasın"),
                    ("simdi", "Şimdi Yayınlansın"),
                ],
                default="yayinlanmasin",
                max_length=20,
                verbose_name="Yayınlanma Seçimi",
            ),
        ),
    ]
