# Generated by Django 5.2.3 on 2025-09-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_remove_dergisayisi_zamanli_yayinlanma_tarihi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dergisayisi",
            name="cilt",
            field=models.PositiveIntegerField(
                default=1, help_text="Örn: 1", verbose_name="Cilt"
            ),
        ),
        migrations.AlterField(
            model_name="dergisayisi",
            name="sayi_no",
            field=models.PositiveIntegerField(
                default=1, help_text="Örn: 1", verbose_name="Sayı No"
            ),
        ),
    ]
