# Generated by Django 5.2.3 on 2025-09-27 13:14

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_alter_dergisayisi_cilt_alter_dergisayisi_sayi_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="dergisayisi",
            name="pdf_dosyasi",
            field=models.FileField(
                blank=True,
                help_text="Derginin tam halini içeren PDF dosyası (isteğe bağlı)",
                null=True,
                upload_to=articles.models.journal_pdf_path,
                verbose_name="Dergi PDF Dosyası",
            ),
        ),
    ]
