# Generated by Django 5.2.3 on 2025-09-27 14:23

import articles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_dergisayisi_pdf_dosyasi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DergiIcerigi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Bu alan otomatik oluşturulur.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "icerik_turu",
                    models.CharField(
                        choices=[
                            ("soylesi", "Söyleşi"),
                            ("mezun_hikayesi", "Mezun Hikayesi"),
                            ("etkinlik", "Etkinlik"),
                            ("haber", "Haber"),
                            ("editorden", "Editörden"),
                            ("diger", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="İçerik Türü",
                    ),
                ),
                ("aciklama", models.TextField(verbose_name="Açıklama/Özet")),
                (
                    "icerik",
                    models.TextField(
                        help_text="Ana içerik metni", verbose_name="İçerik"
                    ),
                ),
                (
                    "pdf_dosyasi",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=articles.models.content_pdf_path,
                        verbose_name="PDF Dosyası",
                    ),
                ),
                (
                    "anahtar_kelimeler",
                    models.CharField(
                        blank=True,
                        help_text="Kelimeleri virgül (,) ile ayırınız.",
                        max_length=255,
                        verbose_name="Anahtar Kelimeler",
                    ),
                ),
                (
                    "goruntulenme_sayisi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Görüntülenme Sayısı"
                    ),
                ),
                (
                    "yayinda_mi",
                    models.BooleanField(default=False, verbose_name="Yayında mı?"),
                ),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncellenme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "dergi_sayisi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="icerikler",
                        to="articles.dergisayisi",
                        verbose_name="Dergi Sayısı",
                    ),
                ),
                (
                    "olusturan_admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="olusturulan_icerikler",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan Admin",
                    ),
                ),
                (
                    "yazarlar",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dergi_icerikleri",
                        to="articles.yazar",
                        verbose_name="Yazarlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dergi İçeriği",
                "verbose_name_plural": "Dergi İçerikleri",
                "ordering": ["-olusturulma_tarihi"],
            },
        ),
    ]
