# Generated by Django 5.2.3 on 2025-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_dergiicerigi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dergiicerigi",
            name="aciklama",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama/Özet"),
        ),
    ]
