# Generated by Django 5.2.3 on 2025-09-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_alter_dergiicerigi_aciklama"),
    ]

    operations = [
        migrations.AddField(
            model_name='dergisayisi',
            name='makale_siralama',
            field=models.CharField(
                choices=[
                    ('olusturulma_tarihi_desc', 'Oluşturulma Tarihi (En Yeni)'),
                    ('olusturulma_tarihi_asc', 'Oluşturulma Tarihi (En Eski)'),
                    ('baslik_asc', 'Başlık (A-Z)'),
                    ('baslik_desc', 'Başlık (Z-A)'),
                    ('yazar_asc', 'Yazar (A-Z)'),
                    ('yazar_desc', 'Yazar (Z-A)'),
                ],
                default='olusturulma_tarihi_desc',
                help_text='Bu dergi sayısındaki makalelerin nasıl sıralanacağını belirler',
                max_length=30,
                verbose_name='Makale Sıralaması'
            ),
        ),
    ]
