# Generated by Django 5.2.3 on 2025-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_auto_20250927_2123"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="makale",
            options={
                "ordering": ["siralama", "-olusturulma_tarihi"],
                "verbose_name": "Makale",
                "verbose_name_plural": "Makaleler",
            },
        ),
        migrations.RemoveField(
            model_name="dergisayisi",
            name="makale_siralama",
        ),
        migrations.AddField(
            model_name="makale",
            name="siralama",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Dergi sayısındaki makale sıralaması (0 = en üstte)",
                verbose_name="Sıralama",
            ),
        ),
    ]
