# Generated by Django 5.2.3 on 2025-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_alter_makale_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dergiicerigi",
            options={
                "ordering": ["siralama", "-olusturulma_tarihi"],
                "verbose_name": "Dergi İçeriği",
                "verbose_name_plural": "Dergi İçerikleri",
            },
        ),
        migrations.AddField(
            model_name="dergiicerigi",
            name="siralama",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Dergi sayısındaki içerik sıralaması (0 = en üstte)",
                verbose_name="Sıralama",
            ),
        ),
    ]
