# Generated by Django 5.2.3 on 2025-09-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0014_alter_dergiicerigi_options_dergiicerigi_siralama"),
    ]

    operations = [
        migrations.AddField(
            model_name="dergisayisi",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Bu alan otomatik oluşturulur.",
                max_length=255,
                null=True,
            ),
        ),
    ]
