# Generated by Django 5.2.3 on 2025-09-28 10:11

import articles.models
import core.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_auto_20250927_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dergiicerigi",
            name="pdf_dosyasi",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=articles.models.content_pdf_path,
                validators=[core.security.validate_pdf_file],
                verbose_name="PDF Dosyası",
            ),
        ),
        migrations.AlterField(
            model_name="dergisayisi",
            name="kapak_gorseli",
            field=models.ImageField(
                blank=True,
                help_text="Yüklenmezse varsayılan kapak kullanılır",
                null=True,
                upload_to=articles.models.journal_cover_path,
                validators=[core.security.validate_image_file],
                verbose_name="Kapak Görseli",
            ),
        ),
        migrations.AlterField(
            model_name="dergisayisi",
            name="pdf_dosyasi",
            field=models.FileField(
                blank=True,
                help_text="Derginin tam halini içeren PDF dosyası (isteğe bağlı)",
                null=True,
                upload_to=articles.models.journal_pdf_path,
                validators=[core.security.validate_pdf_file],
                verbose_name="Dergi PDF Dosyası",
            ),
        ),
        migrations.AlterField(
            model_name="makale",
            name="pdf_dosyasi",
            field=models.FileField(
                upload_to=articles.models.article_pdf_path,
                validators=[core.security.validate_pdf_file],
                verbose_name="PDF Dosyası",
            ),
        ),
    ]
