# Generated by Django 5.2.3 on 2025-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimFormu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=150, verbose_name='İsim Soyisim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('konu', models.CharField(max_length=200, verbose_name='Konu')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('cevaplandi', models.BooleanField(default=False, verbose_name='Cevaplandı mı?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
