# Generated by Django 5.2.3 on 2025-06-21 16:17

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_resmi',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.profile_pic_path, verbose_name='Profil Resmi'),
        ),
    ]
