# Generated by Django 5.2.3 on 2025-06-18 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='yazarlar',
            field=models.ManyToManyField(related_name='makaleler', to=settings.AUTH_USER_MODEL, verbose_name='Yazarlar'),
        ),
    ]
