# Generated by Django 5.2.3 on 2025-06-18 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=255, verbose_name='Yazarın Adı Soyadı')),
                ('user_hesabi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yazar_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
                'ordering': ['isim_soyisim'],
            },
        ),
        migrations.AlterField(
            model_name='makale',
            name='yazarlar',
            field=models.ManyToManyField(related_name='makaleler', to='articles.yazar', verbose_name='Yazarlar'),
        ),
    ]
