# Generated by Django 5.2.3 on 2025-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_yazar_alter_makale_yazarlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='anahtar_kelimeler',
            field=models.CharField(blank=True, help_text='Kelimeleri virgül (,) ile ayırınız.', max_length=255, verbose_name='Anahtar Kelimeler'),
        ),
    ]
